### ISSUE TITLE
Chrome page does not look like Chrome "No Internet" page

### ISSUE THREAD

**Issue by Delioth** [will/redirect_blame#8]
Simply put, the page this project renders for a Google Chrome browser looks nothing like the actual Google Chrome "no internet" error page.

**Comment by will** [comment]
It used to look right, then they went and changed it :<

**Comment by will** [comment]
if you want to fix it, i'd accept the PR. You just kinda have to get the whole source. Idk if the dino game thing would work but maybe?

**Comment by chsaiujwal** [comment]
> if you want to fix it, i'd accept the PR. You just kinda have to get the whole source. Idk if the dino game thing would work but maybe?

check this out https://github.com/will/redirect_blame/pull/9
